### ISSUE TITLE
Use built-in cppcodec string verification

### ISSUE THREAD

**Issue by jpetso** [286897655/licodeclient#1]
Hi, cppcodec maintainer here. I was just looking at who's using cppcodec and how, and saw that you have a snippet that looks like this:

```
const static char* regex = "^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{4}|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)$";

std::regex base64regex(regex);

if (!std::regex_match(token, base64regex, std::regex_constants::match_flag_type::match_default))
{
    fail(failtype::BAD_PARAMETER);
    return;
}

std::string decodetoken = base64::decode<std::string>(token);
```

I thought it may be worth noting that cppcodec already verifies its input as it decodes it, so by doing a separate regex match you're basically doing twice the work that's necessary.

You can instead just catch the `cppcodec::parse_error`, like so:

```
std::string decodetoken;
try {
    base64::decode(decodetoken, token);
} catch (const cppcodec::parse_error&) {
    fail(failtype::BAD_PARAMETER);
    return;
}
```

cppcodec checks include all the ones that your regex also checks for - making sure that all characters are in the base64 alphabet, that blocks are always 4 characters long, and that the right amount of padding characters is used.

In the future I hope to include a separate verification function, but if you're already using decode() then using the error handling of decode() itself should work for your use case.

**Comment by 286897655** [comment]
@jpetso  woo..,thank you very much...,thanks cppcodec~~~~
