### ISSUE TITLE
Can you give me a test demo?

### ISSUE THREAD

**Issue by jxd88757550** [286897655/licodeclient#2]
I've finished building the project, but  not test .

**Comment by 286897655** [comment]
> I've finished building the project, but not test .

this example is just a example of write cpp code to communicate with licode erizo,it's equals erizo client.js. this example list such as "publish","subscriber","OnAddStream","signaling_message",etc.-the most common use interface.if you want to test this,you must:
1、setup licode ，and run licode core
2、write client webrtc cpp code，make a licodeclient and join a room you will get a licoderoom
3、communicate with licode，sendsdp and receive sdp，setup webrtc media communication。

if you are familiar with webrtc and licode，this is very simple。QQ:286897655

**Comment by jxd88757550** [comment]
我的licode 已经搭建了， 用网页是可以正常访问的，  ，webrtc windows已经编译完了，peerconnection_client.exe  也已经可以通了，  现在想做一个windows版本的licode client demo。你的程序我已经编译出来了。但是我不知道怎么测试，  是否有一个简答的demo 。能连接licode 并加入房间进行视频聊天， 万分感谢。

**Comment by 286897655** [comment]
> 我的licode 已经搭建了， 用网页是可以正常访问的， ，webrtc windows已经编译完了，peerconnection_client.exe 也已经可以通了， 现在想做一个windows版本的licode client demo。你的程序我已经编译出来了。但是我不知道怎么测试， 是否有一个简答的demo 。能连接licode 并加入房间进行视频聊天， 万分感谢。

这个我们的项目直接就用了，没有关于这个的demo呢。比较简单的就是你可以改造peerconnection_client.exe的代码 把它与peerconnect_server的通信步骤替换成licode的。然后就能跑起来了。其实你理解了peerconnect_client的代码，熟悉webrtc建立音视频的步骤，用licode 的接口 很容易就能跑个demo起来。

我这里这个也就是把涉及到的接口都梳理出来了，然后用的哪些参数列了下。之前我们开发的时候想找个cpp的demo也是没有找到 所以写好后放出来 为后来者一个参考

**Comment by 286897655** [comment]
还是中文沟通容易

**Comment by jxd88757550** [comment]
哈哈，  加你qq了，通过下呗。
